model:
  name: swin_transformer
  img_size: 32
  patch_size: 4
  in_chans: 3
  num_classes: 100
  embed_dim: 96
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  window_size: 7
  mlp_ratio: 4.0
  drop_rate: 0.0
  attn_dropout: 0.0
  proj_dropout: 0.0
  mlp_dropout: 0.0
  drop_path_rate: 0.1
  use_rel_pos_bias: true
